server:
  port: 8089
spring:
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/demo
  application:
    name: gateway-server
  cloud:
    consul:
      discovery:
        instance-id: "${spring.application.name}:${random.int[1,99999]}"
        tags: gateway-server
      host: localhost
      port: 8500
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: scheduler-server
          uri: lb://SCHEDULER-SERVER
          predicates:
            - Path=/scheduler/**
          filters:
            - RewritePath=/scheduler/(?<path>.*), /$\{path}
            - RemoveRequestHeader= Cookie,Set-Cookie
    discovery:
      enabled: true

management:
  info:
    env:
      enabled: true
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: '*'
        allowed-headers: '*'
        allowed-methods: '*'

auth:
  audience: demo-service-aud

logging:
  level:
    web: debug

